// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "NebulaWWDC23",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "NebulaWWDC23",
            targets: ["AppModule"],
            bundleIdentifier: "br.ufpe.cin.academy.NebulaWWDC23",
            teamIdentifier: "9YF48LKAWG",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .bird),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)
